CREATE TABLE users (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "user" TEXT NOT NULL UNIQUE,
  ctime TIMESTAMP NOT NULL default CURRENT_TIMESTAMP,
  ztime TIMESTAMP
);

CREATE TABLE sent (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"user" INTEGER NOT NULL,
	stage INTEGER NOT NULL,
	ctime TEXT NOT NULL default CURRENT_TIMESTAMP
);
CREATE INDEX sent_user ON sent ("user", stage);
